# Part of Odoo. See LICENSE file for full copyright and licensing details.
"""Make OCA financial-report openings follow explicit Nepali fiscal years.

Odoo's ``fiscalyear_last_day`` / ``fiscalyear_last_month`` pair is only a
fallback.  Nepal's Shrawan--Ashar year must instead be read from the explicit
``account.fiscal.year`` records generated by ``l10n_np_fiscal_year``: their
Gregorian boundaries move by a day across Bikram Sambat years.
"""

from odoo import api, fields, models


def _explicit_fiscal_year_start(company, date):
    """Return an explicit fiscal-year start, never the fixed-setting fallback."""
    fiscal_year = company.compute_fiscalyear_dates(date)
    return fiscal_year["date_from"] if fiscal_year.get("record") else False


class TrialBalanceReportWizard(models.TransientModel):
    _inherit = "trial.balance.report.wizard"

    @api.depends("date_from", "company_id")
    def _compute_fy_start_date(self):
        super()._compute_fy_start_date()
        for wizard in self:
            if wizard.date_from and wizard.company_id:
                exact_start = _explicit_fiscal_year_start(
                    wizard.company_id, wizard.date_from
                )
                if exact_start:
                    wizard.fy_start_date = exact_start


class GeneralLedgerReportWizard(models.TransientModel):
    _inherit = "general.ledger.report.wizard"

    def _init_date_from(self):
        """Default to the exact start of the active company fiscal year."""
        company = self.company_id or self.env.company
        exact_start = _explicit_fiscal_year_start(
            company, fields.Date.context_today(self)
        )
        return exact_start or super()._init_date_from()

    @api.depends("date_from", "company_id")
    def _compute_fy_start_date(self):
        super()._compute_fy_start_date()
        for wizard in self:
            if wizard.date_from and wizard.company_id:
                exact_start = _explicit_fiscal_year_start(
                    wizard.company_id, wizard.date_from
                )
                if exact_start:
                    wizard.fy_start_date = exact_start
