# Part of Odoo. See LICENSE file for full copyright and licensing details.
"""Make OCA financial-report openings follow explicit Nepali fiscal years.

Odoo's ``fiscalyear_last_day`` / ``fiscalyear_last_month`` pair is only a
fallback.  Nepal's Shrawan--Ashar year must instead be read from the explicit
``account.fiscal.year`` records generated by ``l10n_np_fiscal_year``: their
Gregorian boundaries move by a day across Bikram Sambat years.
"""

from odoo import api, fields, models


class TrialBalanceReportWizard(models.TransientModel):
    _inherit = "trial.balance.report.wizard"

    @api.depends("date_from", "company_id")
    def _compute_fy_start_date(self):
        for wizard in self:
            wizard.fy_start_date = (
                wizard.company_id.compute_fiscalyear_dates(wizard.date_from)[
                    "date_from"
                ]
                if wizard.date_from and wizard.company_id
                else False
            )


class GeneralLedgerReportWizard(models.TransientModel):
    _inherit = "general.ledger.report.wizard"

    def _init_date_from(self):
        """Default to the exact start of the active company fiscal year."""
        company = self.company_id or self.env.company
        return company.compute_fiscalyear_dates(
            fields.Date.context_today(self)
        )["date_from"]

    @api.depends("date_from", "company_id")
    def _compute_fy_start_date(self):
        for wizard in self:
            wizard.fy_start_date = (
                wizard.company_id.compute_fiscalyear_dates(wizard.date_from)[
                    "date_from"
                ]
                if wizard.date_from and wizard.company_id
                else False
            )
